name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:
      branches: [ master ]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: git config --global user.email "lesnevskii.igor@gmail.com"
            | && git config --global user.name "Igor Lesnevskiy"
            | && yarn

      - name: Deploy on GithubPages
        run:  CI=false && yarn deploy
