name: CI

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:
      branches: [ master ]


jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run:  yarn
        
      - name: Deploy on GithubPages
        run:  yarn deploy
